/**
 * Static PHP + CSS scaffolding for an FSE theme.
 *
 * FSE themes still need `style.css` (with the WordPress theme header),
 * a minimal `functions.php` (enqueue styles, load textdomain, register
 * block styles), and a `readme.txt`. Content is templated with the
 * brand name, textdomain, and design tokens so the generated theme is
 * self-consistent from install → activate.
 */

import type { DesignSystem, SiteBrief } from "./types.ts";

export function styleCss(brief: SiteBrief, design: DesignSystem, textDomain: string, version: string): string {
  const paletteVars = Object.entries(design.palette)
    .map(([k, v]) => `  --cozy-${kebab(k)}: ${v};`)
    .join("\n");
  return `/*
Theme Name: ${brief.name}
Theme URI: https://github.com/cozy-studio/${textDomain}
Author: Cozy Studio
Author URI: https://cozy.studio
Description: ${brief.tagline} — a warm, block-based WordPress theme generated by Cozy Studio.
Requires at least: 6.4
Tested up to: 6.6
Requires PHP: 7.4
Version: ${version}
License: GNU General Public License v2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
Text Domain: ${textDomain}
Tags: block-templates, full-site-editing, one-column, blog, portfolio, custom-colors, custom-menu, editor-style, translation-ready, wide-blocks, block-styles
*/

:root {
${paletteVars}
  --cozy-radius: ${design.radius}px;
  --cozy-container: ${design.spacing.containerMaxWidth}px;
}

/* Minimal safety net styles. The bulk of styling comes from theme.json. */
body { background: var(--cozy-background); color: var(--cozy-ink); }
a { color: var(--cozy-primary); }
a:focus-visible, button:focus-visible { outline: 2px solid var(--cozy-accent); outline-offset: 2px; border-radius: 3px; }
img, svg, video { max-width: 100%; height: auto; }
.skip-link { position: absolute; left: -9999px; }
.skip-link:focus { left: 1rem; top: 1rem; background: var(--cozy-surface); padding: .5rem 1rem; border-radius: 4px; z-index: 100; }
`;
}

function kebab(s: string): string {
  return s.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase();
}

/** PHP identifiers can't contain hyphens, so derive an underscore-safe prefix. */
function phpPrefix(textDomain: string): string {
  return textDomain.replace(/[^a-zA-Z0-9_]/g, "_");
}

export function functionsPhp(textDomain: string): string {
  const fn = phpPrefix(textDomain);
  return `<?php
/**
 * ${textDomain} — theme functions.
 * Generated by Cozy Studio (WP FSE mode).
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

if ( ! function_exists( '${fn}_setup' ) ) {
    function ${fn}_setup() {
        load_theme_textdomain( '${textDomain}', get_template_directory() . '/languages' );
        add_theme_support( 'title-tag' );
        add_theme_support( 'post-thumbnails' );
        add_theme_support( 'html5', array( 'search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'style', 'script', 'navigation-widgets' ) );
        add_theme_support( 'responsive-embeds' );
        add_theme_support( 'wp-block-styles' );
        add_theme_support( 'editor-styles' );
        add_editor_style( 'style.css' );
    }
}
add_action( 'after_setup_theme', '${fn}_setup' );

if ( ! function_exists( '${fn}_enqueue_styles' ) ) {
    function ${fn}_enqueue_styles() {
        if ( is_admin() ) { return; }
        $version = wp_get_theme()->get( 'Version' );
        wp_enqueue_style(
            '${textDomain}-style',
            get_stylesheet_uri(),
            array(),
            $version
        );
        wp_add_inline_style( '${textDomain}-style', ':root { color-scheme: light; }' );
    }
}
add_action( 'wp_enqueue_scripts', '${fn}_enqueue_styles' );

/**
 * Emit favicon links pointing at theme-bundled icons so the browser never
 * hits the origin-root /favicon.ico (which surfaces as a spurious 500 on
 * some hosts and pollutes the dev console after theme activation).
 */
if ( ! function_exists( '${fn}_favicon_links' ) ) {
    function ${fn}_favicon_links() {
        // Respect an admin-configured Site Icon if one exists.
        if ( function_exists( 'has_site_icon' ) && has_site_icon() ) { return; }
        $uri = get_stylesheet_directory_uri();
        echo '<link rel="icon" href="' . esc_url( $uri . '/favicon.ico' ) . '" sizes="any">' . "\n";
        echo '<link rel="icon" href="' . esc_url( $uri . '/assets/icon.svg' ) . '" type="image/svg+xml">' . "\n";
        echo '<link rel="apple-touch-icon" href="' . esc_url( $uri . '/assets/icon.svg' ) . '">' . "\n";
    }
}
add_action( 'wp_head', '${fn}_favicon_links', 5 );
add_action( 'admin_head', '${fn}_favicon_links', 5 );
add_action( 'login_head', '${fn}_favicon_links', 5 );

/**
 * Silence the harmless "AbortError: Transition was skipped" that WordPress
 * core 6.x can raise in the browser console after themes.php?activated=true
 * when an in-flight View Transition is aborted by the admin redirect. We add
 * a one-shot admin unhandledrejection listener that swallows only that
 * specific rejection - every other rejection still bubbles up unchanged.
 */
if ( ! function_exists( '${fn}_swallow_view_transition_abort' ) ) {
    function ${fn}_swallow_view_transition_abort() {
        ?>
<script>
(function () {
  if (typeof window === 'undefined') return;
  window.addEventListener('unhandledrejection', function (event) {
    var reason = event && event.reason;
    if (!reason) return;
    var name = reason.name || '';
    var msg = (reason.message || String(reason) || '').toLowerCase();
    if (name === 'AbortError' && msg.indexOf('transition was skipped') !== -1) {
      event.preventDefault();
    }
  });
})();
</script>
        <?php
    }
}
add_action( 'admin_print_footer_scripts', '${fn}_swallow_view_transition_abort', 1 );
add_action( 'wp_print_footer_scripts',    '${fn}_swallow_view_transition_abort', 1 );

/**
 * Register additional block styles that the theme.json cannot express directly.
 */
if ( ! function_exists( '${fn}_register_block_styles' ) ) {
    function ${fn}_register_block_styles() {
        register_block_style(
            'core/quote',
            array(
                'name'  => 'cozy-soft',
                'label' => __( 'Soft paper', '${textDomain}' ),
            )
        );
        register_block_style(
            'core/group',
            array(
                'name'  => 'cozy-card',
                'label' => __( 'Cozy card', '${textDomain}' ),
            )
        );
    }
}
add_action( 'init', '${fn}_register_block_styles' );

/**
 * Register patterns categories so the Site Editor exposes theme patterns.
 */
if ( ! function_exists( '${fn}_register_pattern_categories' ) ) {
    function ${fn}_register_pattern_categories() {
        if ( ! function_exists( 'register_block_pattern_category' ) ) { return; }
        register_block_pattern_category( '${textDomain}', array( 'label' => __( 'Cozy patterns', '${textDomain}' ) ) );
    }
}
add_action( 'init', '${fn}_register_pattern_categories' );

/**
 * Skip-link injected for keyboard users. WP core already adds one on FSE themes,
 * but we harden it to always point at #wp--skip-link--target.
 */
if ( ! function_exists( '${fn}_skip_link' ) ) {
    function ${fn}_skip_link() {
        printf(
            '<a class="skip-link screen-reader-text" href="#wp--skip-link--target">%s</a>',
            esc_html__( 'Skip to content', '${textDomain}' )
        );
    }
}
add_action( 'wp_body_open', '${fn}_skip_link' );
`;
}

export function readmeTxt(brief: SiteBrief, textDomain: string, version: string): string {
  return `=== ${brief.name} ===

Contributors: cozystudio
Tags: block-templates, full-site-editing, one-column, blog, portfolio, custom-colors, editor-style, translation-ready
Requires at least: 6.4
Tested up to: 6.6
Stable tag: ${version}
Requires PHP: 7.4
License: GPLv2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html

${brief.tagline}

== Description ==

${brief.description}

Generated by Cozy Studio (WP FSE mode). Warm paper aesthetics, deliberate typography, and a full site editor experience with no build step.

== Changelog ==

= ${version} =
* Initial release generated for "${brief.name}".

== Copyright ==

${brief.name} theme, ${new Date().getFullYear()} Cozy Studio.
${brief.name} theme is distributed under the terms of the GNU GPL.

This theme bundles no third-party fonts or scripts by default; it uses system fonts and inline styles only.

Text Domain: ${textDomain}
`;
}

/** Empty index.php required by WordPress security guidelines even for FSE themes. */
export function indexPhp(): string {
  return `<?php\n// Silence is golden.\n`;
}

export function screenshotSvg(brief: SiteBrief, design: DesignSystem): string {
  const p = design.palette;
  const name = brief.name.replace(/&/g, "&amp;").replace(/</g, "&lt;");
  const tagline = brief.tagline.replace(/&/g, "&amp;").replace(/</g, "&lt;");
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 900" role="img" aria-label="${name}">
  <defs>
    <linearGradient id="bg" x1="0" x2="0" y1="0" y2="1">
      <stop offset="0" stop-color="${p.background}"/>
      <stop offset="1" stop-color="${p.surface}"/>
    </linearGradient>
  </defs>
  <rect width="1200" height="900" fill="url(#bg)"/>
  <rect x="80" y="80" width="1040" height="70" fill="${p.surface}" stroke="${p.border}"/>
  <circle cx="130" cy="115" r="14" fill="${p.primary}"/>
  <text x="170" y="122" font-family="serif" font-size="22" fill="${p.ink}">${name}</text>
  <text x="80" y="290" font-family="serif" font-size="80" fill="${p.ink}">${name}</text>
  <text x="80" y="360" font-family="sans-serif" font-size="28" fill="${p.muted}">${tagline}</text>
  <rect x="80" y="410" width="220" height="56" rx="8" fill="${p.primary}"/>
  <text x="112" y="446" font-family="sans-serif" font-size="20" fill="${p.primaryContrast}">Learn more →</text>
  <g transform="translate(80,540)">
    <rect width="320" height="220" rx="8" fill="${p.surface}" stroke="${p.border}"/>
    <rect x="360" width="320" height="220" rx="8" fill="${p.surface}" stroke="${p.border}"/>
    <rect x="720" width="320" height="220" rx="8" fill="${p.surface}" stroke="${p.border}"/>
  </g>
</svg>`;
}
